// [westrp]/rsm_stables/web/src/components/kit/Button.vue
<script setup>
import { computed } from "vue";
import Icon from "./Icon.vue";

// variant: primary | secondary | ghost · state: active, disabled (+ forced "hover" for the state reference)
const props = defineProps({
  variant: { type: String, default: "secondary" },
  size: { type: String, default: "md" },
  icon: { type: String, default: null },
  active: { type: Boolean, default: false },
  forceHover: { type: Boolean, default: false },
  type: { type: String, default: "button" },
});

const SIZES = {
  sm: "h-9 px-4 text-[11px] gap-2",
  md: "h-11 px-6 text-[12px] gap-2.5",
  lg: "h-13 px-8 text-[13px] gap-3",
};

const cls = computed(() => [
  "btn tx-plate kit-heading inline-flex shrink-0 cursor-pointer items-center justify-center whitespace-nowrap transition-colors active:translate-y-px",
  props.variant === "primary" ? "btn-primary" : props.variant === "ghost" ? "btn-ghost" : "",
  props.active && "is-active",
  props.forceHover && "is-hover",
  SIZES[props.size],
]);
</script>

<template>
  <button :type="type" :class="cls">
    <Icon v-if="icon" :name="icon" :size="size === 'sm' ? 14 : 16" />
    <slot />
  </button>
</template>

// [westrp]/rsm_nuikit/web/src/components/kit/Button.jsx
import { Icon } from "./Surface.jsx";

const SIZES = {
  sm: "h-9 px-4 text-[11px] gap-2",
  md: "h-11 px-6 text-[12px] gap-2.5",
  lg: "h-13 px-8 text-[13px] gap-3",
};

// variant: primary | secondary | ghost · state: active, disabled (+ forced "hover" for the state reference)
export function Button({
  variant = "secondary",
  size = "md",
  icon,
  active = false,
  forceHover = false,
  className = "",
  children,
  type = "button",
  ...rest
}) {
  const v = variant === "primary" ? "btn-primary" : variant === "ghost" ? "btn-ghost" : "";
  return (
    <button
      type={type}
      className={`btn tx-plate kit-heading inline-flex shrink-0 cursor-pointer items-center justify-center whitespace-nowrap transition-colors active:translate-y-px ${v} ${
        active ? "is-active" : ""
      } ${forceHover ? "is-hover" : ""} ${SIZES[size]} ${className}`}
      {...rest}
    >
      {icon && <Icon name={icon} size={size === "sm" ? 14 : 16} />}
      {children}
    </button>
  );
}

// Square icon-only button on the keycap frame
export function IconButton({ icon, label, size = 40, active = false, className = "", ...rest }) {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      className={`btn tx-plate grid shrink-0 cursor-pointer place-items-center transition-colors ${active ? "is-active" : ""} ${className}`}
      style={{ width: size, height: size }}
      {...rest}
    >
      <Icon name={icon} size={Math.round(size * 0.45)} />
    </button>
  );
}
